### ISSUE TITLE
Wrong use of .h header files

### ISSUE THREAD

**Issue by tirthasheshpatel** [Shrey-Viradiya/DSA_Project#2]
`.h` files must have declarations of all the functions in the corresponding `.c` file and these `.h` files must be included in `main.c` instead of `.c` files.
Here's an example:

example.h:
```
#ifndef GUARD_EXAMPLE_H
#define GUARD_EXAMPLE_H

#include <stdio.h>

int add(int, int);

#endif
```

example.c:
```
#include <stdio.h>
#include "example.h"

int add(int a, int b)
{
    return a+b;
}
```

main.c:
```
#include <stdio.h>
#include "example.h"

int main()
{
    int a = 10, b = 20;
    printf("%d", add(a,b));
}
```

**Comment by Shrey-Viradiya** [comment]
Oh thanks, I was just going to Google the use of Header Files.
