### ISSUE TITLE
Makefile in wrong location

### ISSUE THREAD

**Issue by tirthasheshpatel** [Shrey-Viradiya/DSA_Project#3]
Move the makefile in this [folder](https://github.com/Shrey-Viradiya/DSA_Project/tree/master/cmake-build-debug) to this [location](https://github.com/Shrey-Viradiya/DSA_Project/tree/master) for successful build checks and continuous integrations.

**Comment by Shrey-Viradiya** [comment]
I didn't put those there. CLion did. And I trust CLion. I'll consult you in the near future for better understanding. Thanks
